kind: Deployment
apiVersion: apps/v1
metadata:
  name: linked-server
  namespace: linked
  labels:
    app.kubernetes.io/name: linked-server
    app.kubernetes.io/part-of: linked-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linked-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linked-server
        app.kubernetes.io/part-of: linked-server
    spec:
      containers:
        - name: linked-server
          image: wonyus/node-emqx:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: DB_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: SERVER_PORT
            - name: SERVER_WS_PORT
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: SERVER_WS_PORT
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: API_URL
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: API_SECRET
            - name: JWT_EXP_DATE
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: JWT_EXP_DATE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: JWT_SECRET
            - name: JWT_ACCESS_EXP_DATE
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: JWT_ACCESS_EXP_DATE
            - name: JWT_REFRESH_EXP_DATE
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: JWT_REFRESH_EXP_DATE
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: SESSION_SECRET
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: APP_NAME
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: linked-server
                  key: VERSION
          ports:
            - containerPort: 4000
