name: build backend

on:
  push:
    branches: ["development"]
    paths: ["src/**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.2.0
        with:
          context: .
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wonyus/node-emqx:latest, wonyus/node-emqx:${{ steps.create_tag.outputs.version }}
