name: build backend

on:
  push:
    branches: ["development"]
    # paths: ["src/**", "package.json"]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
        
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.ref }}
        #   fetch-depth: 0

      - name: Get last tag
        id: get_last_tag
        run: echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wonyus/node-emqx:latest, wonyus/node-emqx:${{ steps.commit.outputs.short }}
